Repository embarca-teamSIX/teamWorkOne, pull requests merged in 2024-12, with the labels that each got.

#6 Unidade de comprimento
  includes/conversor.h
  src/modules/conversor.c
Labels: help wanted

#8 Temperature
  .gitignore
  CMakeLists.txt
  includes/temperature.h
  includes/tests.h
  output/main.exe
  src/core/main.c
  src/modules/temperature.c
  src/modules/tests.c
Labels: bug, help wanted

#5 Unidade de medida
  Unidade-de-medida
Labels: bug, invalid

#9 Modulo coversor potencia
  includes/conversor_de_potencia.h
  includes/moduloOperacaoSeis.h
  src/modules/conversor_de_potencia.c
  src/modules/moduloOperacaoSeis.c
Labels: question
